BookStore.MVC/Models/ErrorViewModel.cs
namespace BookStore.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookStore.MVC/Controllers/GenreController.cs
using BookStore.Core;
using BookStore.Core.Model;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.MVC.Controllers
{
    public class GenreController : Controller
    {
        public readonly GenreService genreService;

        public GenreController(GenreService genreService)
        {
            this.genreService = genreService;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Genre> genres = await genreService.GetAllGenres();

            return View(genres);
        }

        public async Task<IActionResult> Profile(int genreId)
        {
            Genre genre = await genreService.Get(genreId);

            return View(genre); 
        }
    }
}

BookStore.MVC/Controllers/HomeController.cs
using BookStore.Core.Model;
using BookStore.Core.Service;
using BookStore.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookStore.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly AuthorService authorService;

        public HomeController(AuthorService authorservice)
        {
            this.authorService = authorservice;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Author> authors = await authorService.GetAllAuthors();
            return View(authors);
        }

        public async Task<IActionResult> AuthorProfile(int authorId)
        {
            Author author = await authorService.GetAuthor(authorId);
            return View(author);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookStore.MVC/Views/Genre/Index.cshtml
@using BookStore.Core.Model

@model IEnumerable<Genre>
@{
    ViewData["Title"] = "Genres";
}


<style>
    p {
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif color:dimgrey;
    }
</style>

<div class="text-center">
    <h1>Genres</h1>
</div>

<table>
    @foreach (var genre in Model)
    {
        <tr>
            <td>
                <p>@genre.Name</p>
            </td>

            <td>
                <input class="btn-primary" style="border-radius: 10%; width: 50px; height: 40px;" type="button" value="Info" onclick="@("window.location.href='" + @Url.Action("Profile", "Genre", new { genreId = genre.Id }) + "'");" />
            </td>
        </tr>
    }
</table>

BookStore.MVC/Views/Genre/Profile.cshtml
@using BookStore.Core.Model

@model Genre 

<style>
    p {
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif color:dimgrey;
    }
</style>

<div class="text-center">
    <h1>@Model.Name</h1>
</div>

<table>
    @foreach (var book in Model.Books)
    {
        <tr>
            <td>
                <p>@book.Name</p>
            </td>

@*             <td>
                <input class="btn-primary" style="border-radius: 10%; width: 50px; height: 40px;" type="button" value="Info" onclick="@("window.location.href='" + @Url.Action("GenreInfo", "Genre", new { genreId = genre.Id }) + "'");" />
            </td> *@
        </tr>
    }
</table>

BookStore.MVC/Views/Home/AuthorProfile.cshtml
@using BookStore.Core.Model

@model Author
@{
    ViewData["Title"] = Model.Name + " profile";
}

<h1>@Model.Name</h1>

<p>@Model.Description</p>

@if(Model.Books.Any())
{
    <h2>Books</h2>
    @foreach(Book book in Model.Books)
    {
        <p>@book.Name</p>
    }
}

BookStore.MVC/Views/Home/Index.cshtml
@using BookStore.Core.Model

@model IEnumerable<Author>
@{
    ViewData["Title"] = "Home Page";
}

@* <div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div> *@

<style>
    p {
        font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif
        color:dimgrey;
    }
</style>

<div class="text-center">
    <h1>Authors</h1>
</div>

<table>
    @foreach(var author in Model)
    {
        <tr>
            <td>
                <p>@author.Name</p>
            </td>
            <td>
                <p>@author.Description</p>
            </td>
            <td>
                <input class="btn-primary" style="border-radius: 10%; width: 50px; height: 40px;" type="button" value="Info" onclick="@("window.location.href='" + @Url.Action("AuthorProfile", "Home", new { authorId = author.Id }) + "'");" />
            </td>
        </tr>
    }
</table>

BookStore.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genres</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookStore.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>